import "@/app/globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const wrapperClass = "grow h-full transition-500 overflow-hidden";
  return <div className={wrapperClass}>{children};</div>;
}
